registers: add mseccfg
rivosinc/riscv pull request #13
Opened 2022-12-09 18:27 UTC by beezow

This register is included with the Smepmp extension used on the Opentitan.

2022-12-09 18:58 UTC, furquan-rivos approved these changes, later dismissed

2022-12-09 19:03 UTC, FawazTirmizi approved these changes
This looks fine to me, but technically the register is 64-bit, with `msecfgh` on rv32, although the upper bits are reserved. Given that we need this for OpenTitan, we probably want the distinction. 

[This](https://github.com/rivosinc/riscv/commit/4c544e055eecb9ae4b649861d5a40a10002696e3) PR by Ted dealt with a similar situation for `menvcfg`

2022-12-09 19:03 UTC, FawazTirmizi requested changes
Misclicked, did not mean for that to be an approval.

2022-12-09 22:51 UTC, beezow commented
> This looks fine to me, but technically the register is 64-bit, with `msecfgh` on rv32, although the upper bits are reserved. Given that we need this for OpenTitan, we probably want the distinction.
> 
> [This](https://github.com/rivosinc/riscv/commit/4c544e055eecb9ae4b649861d5a40a10002696e3) PR by Ted dealt with a similar situation for `menvcfg`

All the bitfields I added are in `mseccfg` for both rv32 and rv64. This PR just does not implement `mseccfgh`.

2023-01-09 18:05 UTC, FawazTirmizi approved these changes
Letting this through for now, there isn't anything missing by not defining `msecfgh` and hopefully this will get rewritten soon anyways.

2023-01-09 21:32 UTC, merged